#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_DIR="/Users/keke/orca/workspaces/TradingAgents/explore"
ENV_FILE="$REPO_DIR/.env"
cd "$REPO_DIR"

banner "Reddit OAuth 凭证配置（散户情绪数据源）"

# ── Stage 1: Reddit 账号 ───────────────────────────────────────────────────
stage "确认 Reddit 账号已登录"
say "为什么需要这一步：匿名 Reddit 接口在这台机器的出口 IP 上被限流，"
say "实测 6 次请求只成功 2 次，于是 6 只股票全部报告「零讨论」——"
say "那是 429 被吞掉，不是真的没人讨论。OAuth 认证后额度是 100 次/分钟。"
note "reddit.com 走本机 LightProxy 代理（127.0.0.1:12888），浏览器默认已用系统代理。"
open_url "https://www.reddit.com/login"
step "已登录会直接跳首页；没账号就注册一个（邮箱即可）。"
pause "登录好了按回车继续"

# ── Stage 2: 创建 script 应用，拿 client_id ────────────────────────────────
stage "创建 script 类型应用"
open_url "https://www.reddit.com/prefs/apps"
step "滚到页面底部，点 'are you a developer? create an app...'。"
step "name 填：tradingagents"
step "类型选 'script'（不要选 web app / installed app）。"
step "redirect uri 填：http://localhost:8080"
step "点 'create app'。"
say ""
step "创建后，应用卡片里 'personal use script' 这行下面的一串就是 client_id。"
note "形如 aBcD1234EfGh_iJkLmN，注意别带上多余空格。"
ask REDDIT_CLIENT_ID "粘贴 client_id："

# ── Stage 3: 拿 secret 并写入 .env ─────────────────────────────────────────
stage "获取 secret 并写入 .env"
step "同一张卡片里找到 'secret' 字段，复制它的值。"
note "输入不回显，粘贴完直接回车。"
ask_secret REDDIT_CLIENT_SECRET "粘贴 secret："
write_env REDDIT_CLIENT_ID "$REDDIT_CLIENT_ID"
write_env REDDIT_CLIENT_SECRET "$REDDIT_CLIENT_SECRET"
note "scripts/data_source_guards.py 检测到这两个变量后会自动切到 OAuth 路径。"
pause "按回车开始验证"

# ── Stage 4: 真实调用验证 ──────────────────────────────────────────────────
stage "验证：取 token + 真实搜索一次"
say "这一步会真的去换 token，并搜索三个子版块里提到 ABBV 的帖子。"

run_verify() {
  PYTHONPATH=.:scripts .venv/bin/python - <<'PY'
import sys
sys.path.insert(0, "scripts")
import net_bootstrap
net_bootstrap.apply()
from dotenv import load_dotenv
load_dotenv(".env", override=True)
import data_source_guards as g
token = g._oauth_token()
if not token:
    print("FAIL: 没换到 token（凭证不对，或该应用类型不支持 client_credentials）")
    sys.exit(1)
print(f"OK: token 已获取（前 8 位 {token[:8]}…）")
total = 0
for sub in ("wallstreetbets", "stocks", "investing"):
    try:
        posts = g._oauth_search(token, sub, "ABBV", 5)
        total += len(posts)
        print(f"  r/{sub}: {len(posts)} 条")
    except Exception as exc:
        print(f"  r/{sub}: 失败 {type(exc).__name__} {exc}")
        sys.exit(1)
print(f"OK: 三个子版块共 {total} 条（0 条也算通过——链路通了，只是本周确实没人讨论）")
PY
}

if run_verify; then
  printf '  %s✓ Reddit OAuth 可用%s\n' "$GREEN" "$RESET"
else
  warn "client_credentials 没通过。script 类型应用有时必须用密码模式。"
  if confirm "补充 Reddit 用户名和密码再试一次？"; then
    ask REDDIT_USERNAME "Reddit 用户名："
    ask_secret REDDIT_PASSWORD "Reddit 密码："
    write_env REDDIT_USERNAME "$REDDIT_USERNAME"
    write_env REDDIT_PASSWORD "$REDDIT_PASSWORD"
    if run_verify; then
      printf '  %s✓ Reddit OAuth 可用（密码模式）%s\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("Reddit OAuth 验证仍未通过 — 检查 client_id/secret 是否完整、应用类型是否为 script")
    fi
  else
    SKIPPED+=("Reddit OAuth 验证未通过 — 重跑本向导或改用密码模式")
  fi
fi
pause "按回车查看总结"

finish
