#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_DIR="/Users/keke/orca/workspaces/TradingAgents/explore"
ENV_FILE="$REPO_DIR/.env"
cd "$REPO_DIR"

banner "Alpaca 开户 + Paper Trading API 接入"

# ── Stage 1: 注册 ──────────────────────────────────────────────────────────
stage "注册 Alpaca 账号"
say "本向导只做到「Paper Trading（模拟盘）可用」——不需要上传证件、不需要入金。"
say "实盘还要过 KYC（护照+地址+税号+自拍）并用 Rapyd 或美元电汇入金，不在本向导范围。"
note "已实测：注册表单的 Country of Tax Residence 接受 China，不会被地区拦。"
open_url "https://app.alpaca.markets/signup"
step "First / Last Name：填护照上的拼音姓名（后面实盘 KYC 要对得上）。"
step "Country of Tax Residence：输入 Chin，从下拉里点 China。"
step "Email：建议 Gmail / Outlook（国内邮箱可能漏收通知）。"
step "Password：设一个强密码。"
step "How did you hear about us：随便选一个。"
step "过 Cloudflare 人机验证 → 点 Sign up。"
pause "注册提交完按回车"

# ── Stage 2: 验证邮箱进控制台 ──────────────────────────────────────────────
stage "验证邮箱并进入控制台"
step "去邮箱点验证链接（可能在垃圾邮件里）。"
open_url "https://app.alpaca.markets/"
step "登录后确认能看到 Dashboard。"
note "此时账户是未审核状态——不影响 Paper Trading。"
pause "能看到控制台了按回车"

# ── Stage 3: 切到 Paper 并拿 API Key ──────────────────────────────────────
stage "切换 Paper Trading 并生成 API Key"
step "左上角（或侧边栏）的环境切换，选 **Paper Trading**，不要选 Live。"
step "在 Home 页右侧找到 API Keys 面板 → 点 Generate New Key / View。"
warn "Secret Key 只显示一次，当场复制。关掉就得重新生成。"
say ""
ask ALPACA_API_KEY "粘贴 API Key ID（通常以 PK 开头）："
ask_secret ALPACA_SECRET_KEY "粘贴 Secret Key："
write_env ALPACA_API_KEY "$ALPACA_API_KEY"
write_env ALPACA_SECRET_KEY "$ALPACA_SECRET_KEY"
write_env ALPACA_PAPER_TRADE "True"
write_env APCA_API_BASE_URL "https://paper-api.alpaca.markets"
note "同时写了官方 MCP server 期望的变量名，接 MCP 时不用再配一遍。"
pause "按回车开始验证"

# ── Stage 4: 真实调用验证 ──────────────────────────────────────────────────
stage "验证：调用 paper 账户接口"
say "下面会真的请求 paper-api.alpaca.markets/v2/account。"

resp=$(curl -s --max-time 30 \
  -H "APCA-API-KEY-ID: $ALPACA_API_KEY" \
  -H "APCA-API-SECRET-KEY: $ALPACA_SECRET_KEY" \
  "https://paper-api.alpaca.markets/v2/account" || true)

if printf '%s' "$resp" | grep -q '"account_number"'; then
  printf '  %s✓ Paper 账户可用%s\n' "$GREEN" "$RESET"
  printf '%s' "$resp" | "$REPO_DIR/.venv/bin/python" -c "
import json, sys
d = json.load(sys.stdin)
print(f\"  账户号: {d.get('account_number')}  状态: {d.get('status')}\")
print(f\"  现金: {d.get('cash')}  购买力: {d.get('buying_power')}  币种: {d.get('currency')}\")
print(f\"  交易被冻结: {d.get('trading_blocked')}  下单被禁: {d.get('account_blocked')}\")
" 2>/dev/null || printf '  %s（返回已确认，格式化失败不影响）%s\n' "$DIM" "$RESET"
else
  warn "验证失败，返回内容：$(printf '%s' "$resp" | head -c 200)"
  note "最常见原因：Secret 复制不全，或环境选成了 Live（Live 未过 KYC 会 403）。"
  SKIPPED+=("Alpaca paper 验证未通过 — 重新生成密钥后再跑一次本向导")
fi
pause "按回车查看总结"

finish
